# Generated by Django 5.0.1 on 2024-03-18 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_map_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='map',
            old_name='data',
            new_name='maze',
        ),
    ]
