# Generated by Django 5.0.1 on 2024-01-29 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('user_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('usr_name', models.CharField(max_length=20)),
                ('usr_pass', models.CharField(max_length=20)),
            ],
        ),
    ]
