# Generated by Django 5.0.1 on 2024-01-29 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='usr_name',
            new_name='user_name',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='usr_pass',
            new_name='user_pass',
        ),
    ]
