# Generated by Django 5.0.1 on 2024-01-30 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_alter_userinfo_user_id_alter_userinfo_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='user_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
