# Generated by Django 5.0.1 on 2024-02-04 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_onlineuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='user_email',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
    ]
