# Generated by Django 4.2 on 2024-02-16 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0007_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='user_pass',
            field=models.CharField(max_length=128),
        ),
    ]
