# Generated by Django 4.2 on 2024-02-26 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0009_userinfo_last_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OnlineUser',
        ),
    ]
