# Generated by Django 4.2 on 2024-02-15 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chathome', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserMessage',
        ),
    ]
